# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [1]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 1 & 2: Solutions by Roberto Tabosa') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 1 & 2: Solutions by Roberto Tabosa
Local Time: 2023-09-23 09:05:56
Computer ID: roberto


## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array. 


In [13]:
## Your code here down
import numpy as np
arrayRandom = np.random.randint(1, 11, size=(4, 5))
print (arrayRandom)
print (f"Maximum Value in this array is: {np.max(arrayRandom)}")
print (f"The mean is: {np.mean(arrayRandom)}")
print (f"The standard deviation in axis Y is: {np.std(arrayRandom, -1)}")
print (f"The standard deviation in axis X is: {np.std(arrayRandom, 0)}")

# print(mean)
#print(std) and so on
## Your code here up

[[ 1  4  9  3  6]
 [ 8  5  1 10  9]
 [ 8  4  9  5  8]
 [ 1  1  3  6  5]]
Maximum Value in this array is: 10
The mean is: 5.3
The standard deviation in axis Y is: [2.72763634 3.26190129 1.93907194 2.03960781]
The standard deviation in axis X is: [3.5        1.5        3.57071421 2.54950976 1.58113883]


2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [26]:
## Your code here down
arrayRandom2 = np.random.rand (20)
print (arrayRandom2)

arrayRandom2R = arrayRandom2.reshape (4,5)
print (f"After reshape: {arrayRandom2R}")
np.mean (arrayRandom2R, axis = 1)


## Your code here up

[0.97445549 0.21282607 0.84587555 0.1419858  0.50845502 0.24813731
 0.36536217 0.26106624 0.59180946 0.23821441 0.57225378 0.09344157
 0.96172157 0.59795637 0.02584702 0.81585755 0.9252742  0.53249717
 0.59794429 0.9779329 ]
After reshape: [[0.97445549 0.21282607 0.84587555 0.1419858  0.50845502]
 [0.24813731 0.36536217 0.26106624 0.59180946 0.23821441]
 [0.57225378 0.09344157 0.96172157 0.59795637 0.02584702]
 [0.81585755 0.9252742  0.53249717 0.59794429 0.9779329 ]]


array([0.53671959, 0.34091792, 0.45024406, 0.76990122])

3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [30]:
## Your code here down
array55 = np.random.randint (1, 101, size = (5,5))
print (array55)
np.std (array55, axis = 0)

## Your code here up

[[49 68 94 25 99]
 [ 1  1 19 66 79]
 [65 61 14 65 73]
 [48  4 27 41  3]
 [96 96 13 82 37]]


array([30.75971391, 37.41122826, 30.7024429 , 20.21286719, 34.09633411])

4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [44]:
## Your code here down
array15 = np.random.uniform(-10,10,15)
print(array15)

array15Ab =  np.absolute (array15)
print (array15Ab)

## Your code here up

[ 9.83259236 -6.60343366 -5.42925488  3.89510679  5.78450639  2.67577753
  8.26222595  2.71675739 -0.79697067  3.64945535  5.44811171 -8.17552493
  0.91057653  2.58889427  9.02774018]
[9.83259236 6.60343366 5.42925488 3.89510679 5.78450639 2.67577753
 8.26222595 2.71675739 0.79697067 3.64945535 5.44811171 8.17552493
 0.91057653 2.58889427 9.02774018]


5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [51]:
## Your code here down
array100 = np.random.randint (1,100, size = (3,4))
print(array100)
np.sum(array100)

## Your code here up

[[46 74  4  9]
 [49 18 51 99]
 [45 76 30 45]]


546

7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [67]:
## Your code here down
array46 = np.random.rand (4, 6)
print (array46)
print("\n")

mdColum = np.mean(array46, axis = 0)
print (mdColum)
print()

stdColum = np.std (array46, axis = 0)
print (stdColum)
print("\n")

array46 = (array46 - mdColum)/stdColum
print (f"The data normalized are:\n {array46}")

## Your code here up

[[0.50401314 0.54221554 0.49754779 0.88921938 0.51494839 0.72107824]
 [0.56483333 0.99549526 0.88809569 0.58778997 0.03022619 0.96320132]
 [0.61135765 0.64260537 0.18559755 0.20435332 0.13160241 0.36536627]
 [0.71957265 0.09155696 0.50592252 0.51312052 0.71705033 0.51116659]]


[0.59994419 0.56796828 0.51929089 0.5486208  0.34845683 0.6402031 ]

[0.07886186 0.32248293 0.24900788 0.24357852 0.27922983 0.22530776]


The data normalized are:
 [[-1.21644415 -0.07985768 -0.08731891  1.39831124  0.59625278  0.35895406]
 [-0.44521979  1.3257352   1.48109689  0.16080715 -1.13967281  1.43358675]
 [ 0.14472722  0.23144508 -1.34009148 -1.4133737  -0.77661623 -1.21982855]
 [ 1.51693672 -1.47732261 -0.05368651 -0.14574469  1.32003626 -0.57271226]]


8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [74]:
## Your code here down
array1010 = np.random.randint(1, 100, size = (10, 10))
print(array1010)
print("\n")

np.where (array1010 > 50, 1, 0)

## Your code here up

[[81 41 62 66 62 86 90 51 97 44]
 [58 88 38 82 86  6 28 61 44 84]
 [36 43 99 88 95 66 31 76 88 72]
 [48 69 17 77 43 83 92 22 16 15]
 [54 23 45 50 56  8 75 94 72 66]
 [ 7 68 55 56 87 61 20 46 20 29]
 [23 54 95 31 15 95 68  5 65 11]
 [98 29 44 34 41 38 84 21 78 74]
 [ 8 72 37 60  6 27  6 86  5 35]
 [72 77 38  8 19 96 24 45 35 36]]




array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0]])

9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [86]:
## Your code here down
array50 = np.random.rand (50)
print(array50)
print("\n")

array50 [array50 > 0.5]

## Your code here up

[0.68229427 0.11409991 0.43808798 0.52253682 0.24397528 0.60835668
 0.47644867 0.11806241 0.66869308 0.53433546 0.66448407 0.86618558
 0.56894281 0.88750917 0.90622197 0.98503103 0.73881142 0.37762361
 0.26105678 0.97754849 0.27157509 0.66304554 0.72402147 0.79691626
 0.68268193 0.10669759 0.66465673 0.54472856 0.14517074 0.38613005
 0.22945663 0.23598155 0.63015098 0.13027683 0.60814107 0.61794247
 0.67617122 0.89580303 0.80736735 0.80732984 0.37305049 0.50690563
 0.32537089 0.53830944 0.24315895 0.85724496 0.97083682 0.40434273
 0.09638832 0.09213807]




array([0.68229427, 0.52253682, 0.60835668, 0.66869308, 0.53433546,
       0.66448407, 0.86618558, 0.56894281, 0.88750917, 0.90622197,
       0.98503103, 0.73881142, 0.97754849, 0.66304554, 0.72402147,
       0.79691626, 0.68268193, 0.66465673, 0.54472856, 0.63015098,
       0.60814107, 0.61794247, 0.67617122, 0.89580303, 0.80736735,
       0.80732984, 0.50690563, 0.53830944, 0.85724496, 0.97083682])

10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [99]:
## Your code here down
array2D55 = np.random.uniform (-1, 1, size = (5,5))
print (array2D55)
print("\n")
maxValue = array2D55.max(axis = 1)
print(maxValue)
print ("\n")
minValue = array2D55.min (axis = 1)
print (minValue)
print ("\n")

np.abs (maxValue - minValue)

## Your code here up

[[ 0.32659075  0.0375101  -0.55690049 -0.7880187  -0.07765876]
 [ 0.52302628  0.29163874 -0.00783058  0.60815032  0.99732813]
 [-0.76667688 -0.89282548 -0.01471093  0.89079877  0.16661637]
 [ 0.93900453 -0.17117405  0.19330547 -0.17624561  0.78901703]
 [ 0.60777333  0.22951329  0.39937716 -0.18037246 -0.58049876]]


[0.32659075 0.99732813 0.89079877 0.93900453 0.60777333]


[-0.7880187  -0.00783058 -0.89282548 -0.17624561 -0.58049876]




array([1.11460945, 1.00515871, 1.78362425, 1.11525013, 1.18827209])

## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part. 

In [2]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(200):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 33), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 90), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [3]:
# your code here
df = pd.DataFrame (farms)
print (df)

    farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0      Farm 1   -104.42     51.26         23.7           28.3       black
1      Farm 2   -102.47     51.23         31.3           76.8        gray
2      Farm 3   -102.30     51.18         18.1           85.2  dark brown
3      Farm 4   -104.22     50.83         25.6           46.7  dark brown
4      Farm 5   -104.19     50.53         19.6           42.6       black
..        ...       ...       ...          ...            ...         ...
195  Farm 196   -104.38     51.54         27.1           40.2        gray
196  Farm 197   -103.72     51.06         20.6           38.4        gray
197  Farm 198   -105.00     51.25         31.6           49.0  dark brown
198  Farm 199   -104.57     50.35         21.0           76.3        None
199  Farm 200   -102.05     50.36         20.1           58.3       brown

[200 rows x 6 columns]


1. Select the rows where the temperature is above 20 degrees Celsius.

In [5]:
## Your code here down
df.loc[df["temperature"] > 20]

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0      Farm 1   -104.42     51.26         23.7           28.3       black
1      Farm 2   -102.47     51.23         31.3           76.8        gray
3      Farm 4   -104.22     50.83         25.6           46.7  dark brown
5      Farm 6   -102.11     51.48         26.5           54.7        None
6      Farm 7   -101.35     51.98         22.5           55.1        None
..        ...       ...       ...          ...            ...         ...
195  Farm 196   -104.38     51.54         27.1           40.2        gray
196  Farm 197   -103.72     51.06         20.6           38.4        gray
197  Farm 198   -105.00     51.25         31.6           49.0  dark brown
198  Farm 199   -104.57     50.35         21.0           76.3        None
199  Farm 200   -102.05     50.36         20.1           58.3       brown

[181 rows x 6 columns]

2. Sort the DataFrame by precipitation in descending order.

In [15]:
## Your code here down
df.sort_values("precipitation", ascending = False)

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
82    Farm 83   -101.49     50.07         24.9           89.8       black
189  Farm 190   -101.75     50.97         23.8           89.5       brown
7      Farm 8   -102.31     50.73         28.3           89.4        None
150  Farm 151   -100.01     51.92         21.4           89.3        gray
187  Farm 188   -102.53     50.99         26.6           89.1  dark brown
..        ...       ...       ...          ...            ...         ...
170  Farm 171   -103.35     50.94         26.5           21.2       black
152  Farm 153   -103.48     51.51         20.7           21.1  dark brown
102  Farm 103   -104.10     51.24         24.9           21.0       brown
141  Farm 142   -101.52     51.00         28.4           20.9       brown
165  Farm 166   -101.93     50.10         26.2           20.4        gray

[200 rows x 6 columns]

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [17]:
## Your code here down
df[(df["farm_lat"] >= 51.00) & (df["farm_lat"] <= 51.15)]

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
10    Farm 11   -100.92     51.03         24.7           74.7        None
13    Farm 14   -101.78     51.02         20.3           28.6       brown
22    Farm 23   -103.17     51.01         29.2           36.1       brown
25    Farm 26   -100.22     51.06         30.5           50.8        gray
43    Farm 44   -102.49     51.05         33.0           78.7       brown
57    Farm 58   -103.28     51.01         21.4           62.6        None
64    Farm 65   -103.39     51.15         25.3           54.5  dark brown
90    Farm 91   -102.96     51.12         20.0           75.5        gray
93    Farm 94   -103.89     51.14         29.2           69.4       black
103  Farm 104   -101.37     51.03         32.1           34.9  dark brown
116  Farm 117   -102.15     51.01         24.9           61.0  dark brown
122  Farm 123   -101.15     51.13         20.7           76.4       black
125  Farm 126   -103.44     51.00         30.1           27.2       brown
126  Farm 127   -101.18     51.11         21.6           72.6        None
127  Farm 128   -103.21     51.05         24.2           78.4        gray
141  Farm 142   -101.52     51.00         28.4           20.9       brown
154  Farm 155   -104.32     51.07         27.8           38.2       black
166  Farm 167   -101.11     51.12         26.2           59.3       black
196  Farm 197   -103.72     51.06         20.6           38.4        gray

 4. Calculate the standard deviation of precipitation for each soil type.

In [23]:
## Your code here down
df.head(5)

stdSoil = df.groupby('soil_type')['precipitation'].std()
print (stdSoil)

## Your code here up

soil_type
black         19.665333
brown         21.898394
dark brown    21.405759
gray          20.095832
Name: precipitation, dtype: float64


5. Calculate the cumulative sum of precipitation for each soil type.

In [26]:
## Your code here down
df.head(5)

sumPrec = df.groupby("soil_type")["precipitation"].sum()
print(sumPrec)

## Your code here up

soil_type
black         2460.1
brown         1575.1
dark brown    2246.7
gray          2287.0
Name: precipitation, dtype: float64


6. Determine the top 3 farms with the highest average temperature.

In [ ]:
## Your code here down


## Your code here up

7. Find famrs in each soil type that have the highest temperature.

In [ ]:
## Your code here down


## Your code here up

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [ ]:
## Your code here down


## Your code here up

9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [ ]:
## Your code here down


## Your code here up

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [ ]:
## Your code here down


## Your code here up

# Assignment 4

## ETL

11. Change column types accordingly.

In [ ]:
## Your code here down


## Your code here up

## EDA

12. Find missing values and give information how would you handle them

In [ ]:
## Your code here down


## Your code here up

13. Find outliers if there is any how would you handle them

In [ ]:
## Your code here down


## Your code here up

14. Find descriptive statistics for relavant columns and plot them by using bars.

In [ ]:
## Your code here down


## Your code here up

15. Plot the distribution of relevant columns.

In [ ]:
## Your code here down


## Your code here up